dist: focal
language: php
php:
  - 7.4

install:
  - composer install

script:
  - composer test
  - composer static-analysis

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
